### ISSUE TITLE
Support username / modifier

### ISSUE THREAD

**Issue by NoelLH** [webful-ltd/passwordmaker#10]
As these appear to be the same thing in essence (one appended to the other) it's probably best to implement it as a single field to avoid cluttering the UI too much, and explain how to join separate ones from other apps in a help message for anyone who used both in other apps.

- [x] Add a free text username / modifier field
- [x] Process according to this settings when generating passwords

**Comment by ericjung** [comment]
> it's probably best to implement it as a single field

Interesting solution. I hope it is understood.

**Comment by NoelLH** [comment]
> > it's probably best to implement it as a single field
> 
> Interesting solution. I hope it is understood.

It's not too late to change it @ericjung if you think it's confusing, the latest beta releases are just going through approval and earlier builds should be available to test out already. There's help text that aims to explain it for users of existing apps.

Beta opt ins (I'll make these more obvious somewhere central soon):

* [Android](https://play.google.com/apps/testing/uk.webful.passwordmaker)
* [iOS](https://testflight.apple.com/join/3MnAJg3Z)

I'll leave it a week or so before v2 goes out to everyone, or longer if any major issues.
