### ISSUE TITLE
Support custom character set

### ISSUE THREAD

**Issue by NoelLH** [webful-ltd/passwordmaker#9]
- [x] When moving from simple to advanced settings, this should be pre-populated with the last standard preset's characters but freely editable if custom is chosen
- [x] Generate should then process according to the customised character set

**Comment by ericjung** [comment]
@NoelLH, just wanted to comment that I'm amazed at your project. I'm the original author of PasswordMaker from many years ago. Very impressive what you've done and I'm glad to use it.

**Comment by NoelLH** [comment]
> @NoelLH, just wanted to comment that I'm amazed at your project. I'm the original author of PasswordMaker from many years ago. Very impressive what you've done and I'm glad to use it.

Thanks @ericjung, much appreciated and glad to hear you're using the app! Hopefully I'll make some progress on the planned features before _too_ long :)
